In [2]:
#import libraries
import pandas as pd
from pathlib import Path

In [3]:
#import file
csv_path = Path("./v_tsla_newsapi.csv")
csv_path_price= Path("./TSLA.csv")
#tesla=pd.read_csv(csv_path, parse_dates=True, infer_datetime_format=True) datetime format wrong
tesla=pd.read_csv(csv_path, parse_dates=['date'], infer_datetime_format=True)
stock_price=pd.read_csv(csv_path_price, parse_dates=['Date'])#, index_col="Date", infer_datetime_format=True)

In [4]:
#inspect csv files and drop unnecessary columns
stock_price=stock_price.drop(columns=["Open","High","Low","Adj Close","Volume"])

In [5]:
stock_price=stock_price.sort_values("Date", ascending = False)

In [6]:
#combine df
new_stock_price=stock_price.iloc[0:25,:]

In [7]:
#check stock dataframe
new_stock_price.head()

          Date       Close
252 2020-10-14  461.299988
251 2020-10-13  446.649994
250 2020-10-12  442.299988
249 2020-10-09  434.000000
248 2020-10-08  425.920013

In [8]:
#inspect tesla files
tesla.head()

,Unnamed: 0,date,text,compound,positive,negative,neutral
0,0,2020-09-15 22:30:51,This article was contributed by Lior Gantz of ...,0.4939,0.086,0.000,0.914
1,1,2020-09-15 22:15:16,Growth shares have pummelled value stocks in t...,0.8750,0.262,0.000,0.738
2,2,2020-09-15 21:02:26,"Image: EpicTop10.com\r\nBy Brian Nelson, CFA\r...",0.1779,0.050,0.000,0.950
3,3,2020-09-15 20:43:43,"Hindenburg Research, the short seller that suc...",0.2023,0.142,0.095,0.763
4,4,2020-09-15 20:28:00,The Dow Jones Industrial Average gave up gains...,0.7184,0.175,0.000,0.825

In [9]:
#seperate date and time
tesla['Date'] = pd.to_datetime(tesla['date']).dt.date
tesla['time'] = pd.to_datetime(tesla['date']).dt.time

In [10]:

tesla.head()

,Unnamed: 0,date,text,compound,positive,negative,neutral,Date,time
0,0,2020-09-15 22:30:51,This article was contributed by Lior Gantz of ...,0.4939,0.086,0.000,0.914,2020-09-15,22:30:51
1,1,2020-09-15 22:15:16,Growth shares have pummelled value stocks in t...,0.8750,0.262,0.000,0.738,2020-09-15,22:15:16
2,2,2020-09-15 21:02:26,"Image: EpicTop10.com\r\nBy Brian Nelson, CFA\r...",0.1779,0.050,0.000,0.950,2020-09-15,21:02:26
3,3,2020-09-15 20:43:43,"Hindenburg Research, the short seller that suc...",0.2023,0.142,0.095,0.763,2020-09-15,20:43:43
4,4,2020-09-15 20:28:00,The Dow Jones Industrial Average gave up gains...,0.7184,0.175,0.000,0.825,2020-09-15,20:28:00

In [11]:
#check datatypes for Date 
tesla.dtypes

Unnamed: 0             int64
date          datetime64[ns]
text                  object
compound             float64
positive             float64
negative             float64
neutral              float64
Date                  object
time                  object
dtype: object

In [12]:
#sort by date
tesla=tesla.sort_values("Date", ascending = False)

In [13]:
#drop extra columns
tesla= tesla.drop(["Unnamed: 0","date","neutral"], axis=1)
tesla.head()

,text,compound,positive,negative,Date,time
725,Autonomous vehicles are transforming warehouse...,0.0000,0.000,0.000,2020-10-14,20:17:49
733,CNBC TV\r\n<ul><li>Billionaire investor Ron Ba...,0.5719,0.139,0.000,2020-10-14,15:36:25
742,"Dow Jones futures, along with S&amp;P 500 and ...",0.0000,0.000,0.000,2020-10-14,00:57:00
741,The lithium industry is set to undergo massive...,-0.1280,0.000,0.045,2020-10-14,00:59:43
740,(Source: Toyota)\r\nNikola Corp. (NKLA) has ha...,0.0000,0.000,0.000,2020-10-14,03:22:32

In [14]:
tesla.dtypes

text         object
compound    float64
positive    float64
negative    float64
Date         object
time         object
dtype: object

In [15]:
tesla.head(),stock_price.head()

(                                                  text  compound  positive  \
 725  Autonomous vehicles are transforming warehouse...    0.0000     0.000
 733  CNBC TV\r\n<ul><li>Billionaire investor Ron Ba...    0.5719     0.139
 742  Dow Jones futures, along with S&amp;P 500 and ...    0.0000     0.000
 741  The lithium industry is set to undergo massive...   -0.1280     0.000
 740  (Source: Toyota)\r\nNikola Corp. (NKLA) has ha...    0.0000     0.000

      negative        Date      time
 725     0.000  2020-10-14  20:17:49
 733     0.000  2020-10-14  15:36:25
 742     0.000  2020-10-14  00:57:00
 741     0.045  2020-10-14  00:59:43
 740     0.000  2020-10-14  03:22:32  ,
           Date       Close
 252 2020-10-14  461.299988
 251 2020-10-13  446.649994
 250 2020-10-12  442.299988
 249 2020-10-09  434.000000
 248 2020-10-08  425.920013)

In [16]:
tesla=tesla.groupby(['Date']).mean()*100   #pct_change()*100 #or use .mean()

In [17]:
new_tesla=tesla.sort_values("Date", ascending = False)
new_tesla=new_tesla.reset_index()

In [18]:
#new_tesla.head(),
new_stock_price=new_stock_price.reset_index()

In [19]:
#new_stock_price
new_stock_price=new_stock_price.drop(columns=['index'])

In [20]:
##new_tesla.dtypes
new_stock_price.dtypes

Date     datetime64[ns]
Close           float64
dtype: object

In [21]:
#change new stock data and see if it plots better
new_stock_price['Close']=new_stock_price['Close'].pct_change()*100

In [22]:
new_tesla['Date']=pd.to_datetime(new_tesla['Date'])

In [23]:
#merge both data sets
tesla_df=pd.merge(new_tesla,new_stock_price, how='inner', on='Date')

In [24]:
tesla_df.iloc[:,:]

         Date   compound   positive  negative      Close
0  2020-10-14  29.807143   7.628571  1.276190        NaN
1  2020-10-13  21.031600   9.236000  4.372000  -3.175806
2  2020-10-12  19.065000   7.065000  2.210000  -0.973918
3  2020-10-09  16.771765   5.541176  1.764706  -1.876552
4  2020-10-08  24.961304   9.582609  3.743478  -1.861748
5  2020-10-07   9.401034   6.627586  3.896552  -0.145573
6  2020-10-06   4.402000   4.712000  3.648000  -2.661645
7  2020-10-05  32.066154   8.207692  0.969231   2.826219
8  2020-10-02   5.912778   4.997222  3.758333  -2.487784
9  2020-10-01  16.388148   6.266667  2.907407   7.966949
10 2020-09-30  12.462258   7.129032  3.964516  -4.273026
11 2020-09-29  20.591000   6.295000  1.795000  -2.316963
12 2020-09-28   7.583103   4.434483  2.679310   0.508269
13 2020-09-25  23.930000   7.953333  2.060000  -3.290602
14 2020-09-24   6.606757   7.918919  5.972973  -4.799427
15 2020-09-23   5.921864   6.338983  4.896610  -1.915992
16 2020-09-22  13.041020   6.175510  3.465306  11.533817
17 2020-09-21  20.583846   7.520513  2.605128   5.930746
18 2020-09-18  14.129697   7.972727  5.157576  -1.611077
19 2020-09-17  26.080952  10.204762  3.985714  -4.233858
20 2020-09-16  22.117586   6.358621  1.537931   4.328937
21 2020-09-15  34.086111  11.441667  3.530556   1.810938
22 2020-09-14  17.748667   7.690000  4.076667  -6.701355

In [27]:
%matplotlib
import hvplot.pandas
tesla_df.hvplot(xlabel= "Days", label="Sentiment Analysis vs Tsla close price using newsapi")

Using matplotlib backend: Qt5Agg

:NdOverlay   [Variable]
   :Curve   [index]   (value)